### PR TITLE
Issue 7

### PR DESCRIPTION
**Pull request by pegeler**
Hi @RobinHankin,

I have identified the problem causing issue #7 and propose a fix here. Essentially, the `apply` function inside `setparts` was (correctly) not simplifying when multiple matrices of different dimensions were returned; but would otherwise simplify and ignore the dimension attribute when returning. So in the example input of `as.matrix(c(2,1,1))`,  `apply` simplified the result into a matrix and dropped the dimensions. There are two approaches to fix this, and I went with changing the `apply` call to `lapply`. It's a little more of a mouthful to say, but is much safer. It also obviates the need for the `if` block nested inside that conditional branch.

Sorry for the messy commit history. I did not realize you had squashed upon merging my PR until it was too late. This will teach me the lesson to put all of my features into their own branch! I will do a hard reset upon completion of this merge. In the meantime, just look at e838fa1 onward, as the rest of them have already been merged in #12.

### CODE REVIEW

**Comment by RobinHankin** [comment]
Hi there, thanks for this.  I am not 100% clear on the implications of
'squashing', I chose this largely because it was the default recommendation
on github (and I still haven't quite grokked the social aspects of PRs, as
I generally only use git to organise my own thinking).  But right now I am
having a bit of a CRAN-induced crisis as the `spray` package fails a new QC
and will get pulled unless I fix it....and `spray` depends on a slight
modification to the master branch of `partitions`.  And I am having
difficulty establishing that the new partitions package does not break any
of its many reverse dependencies [in particular the `permutations` package,
also one of mine].  So my priority now is to stabilise these three packages
and upload them to CRAN asap.    Originally, `NAMESPACE` of `partitions`
included a line `export(print)` and removing this breaks the `permutations`
package.  Does restoring this line do any harm?

Best wishes,

Robin




<hankin.robin@gmail.com>

**Comment by pegeler** [comment]
Hi Robin,

You are quite all right by squashing those commits--I was the party at fault **committing** the _faux pas_ with respect to my git behaviour. (Couldn't resist the pun.)

It sounds like you have your hands full right now with those CRAN checks. I will be glad to assist you in troubleshooting all three packages. If you could share some details as to what is failing and why (_i. e._, NOTEs, WARNINGs, and ERRORs), I am going to have quite a bit of free time next week to work on it. I enjoy troubleshooting package development minutiae, so it is no trouble at all.

With respect to the removal of the `export(print)` directive from the _NAMESPACE_ file (in `partitions`), that was done because we are only exporting S3 methods for print, but not the base function. Exporting `print` itself results in a NOTE when running checks. Re-inserting it into the _NAMESPACE_ file may be OK, as CRAN will accept NOTEs with an appropriate explanation, but I think it would be better to get to the root cause. I am guessing that the appropriate import directive in the target package (in this case `permutations`) should clear things up. I will take a look.

**Comment by RobinHankin** [comment]
The problem with `spray` is unrelated (it is a mathjaxr issue) but the problem is that the git version of spray needs an updated partitions package.  With the `export(print)` in the NAMESPACE file I see no warnings on either winbuillder R-release or winbuilder R-devel.  And permutations works fine.  But without it, both the CRAN version of permutations and the github version give me an `R CMD check` error:

```
** byte-compile and prepare package for lazy loading
Error: object ‘print’ is not exported by 'namespace:partitions'
Execution halted
ERROR: lazy loading failed for package ‘permutations’
* removing ‘/home/rhankin/temp/permutations.Rcheck/permutations’
rhankin@cuttlefish:~/temp/permutations.Rcheck $ 
```

so I would like to have it there.  The permutations package has the line `importFrom(partitions,print)` in its NAMESPACE so I don't quite understand what the issue is.  Frankly CRAN issues like this make me very jittery and I am worried that I may end up in some nightmarish cyclic dependency. Any advice welcome!  But I'm cutting it fine because I only have a couple of weeks to upload spray and this needs partitions, and it takes about a week for uploaded packags to percolate through the CRAN ecosystem.  

Best wishes

Robin

**Comment by pegeler** [comment]
I think you are all set as far as moving forward in whatever additional development you need to do to partitions, as long as you push the update to permutations first. The order in which you'd submit to CRAN would be:

permutations v1.0-8 => partitions v1.10-0 => spray

As you might have noticed, I have submitted a PR to RobinHankin/permutations#24 that explains how to fix your problem with the error message attached in your previous post. Essentially, the way that S3 methods are registered means that they come along for the ride whenever the imported package namespace is loaded. So just by your existing imports, you've already covered your bases with the print method.

On the flip side, I was getting a NOTE or WARNING (can't remember which) on one of my machines when leaving `export(print)` in the NAMESPACE because the print generic doesn't belong to partitions (it belongs to base). So I think the most 'proper' thing to do here is to modify permutations as proposed in the PR and push that up to CRAN. Then you won't have any more reverse dependency issues.

In fact, I have used the r-lib/revdepcheck package to confirm that there will be no additional problems. I was unable to run 4 checks, so I'm re-running (may take up to an hour). I will post summary results when they come in.

**Comment by pegeler** [comment]
`revdepcheck` report:
==============

Below is the summary output from running the revdepcheck. As expected, the only problem I see is with the CRAN version of `permutations` (which is solved with RobinHankin/permutations#24). There were some packages that did not run (I think because of timeout due to deep dependency trees) and there was a completely unrelated bug in the `revdepcheck` package that required me to check `stokes` and `wedge` manually. Checks passed in both cases.

Let me know if you have any questions.

---

# Platform

|field    |value                        |
|:--------|:----------------------------|
|version  |R version 4.0.2 (2020-06-22) |
|os       |Ubuntu 18.04.4 LTS           |
|system   |x86_64, linux-gnu            |
|ui       |RStudio                      |
|language |en                           |
|collate  |en_US.UTF-8                  |
|ctype    |en_US.UTF-8                  |
|tz       |America/New_York             |
|date     |2020-09-19                   |

# Dependencies

|package    |old    |new    |Δ  |
|:----------|:------|:------|:--|
|partitions |1.9-22 |1.10-0 |*  |
|eddington  |NA     |2.1.1  |*  |
|gmp        |0.6-0  |0.6-0  |   |
|mathjaxr   |NA     |1.0-1  |*  |
|polynom    |1.4-0  |1.4-0  |   |
|Rcpp       |NA     |1.0.5  |*  |
|sets       |1.0-18 |1.0-18 |   |

# Revdeps

## Failed to check (5)

|package                                  |version |error  |warning |note |
|:----------------------------------------|:-------|:------|:-------|:----|
|copula                                   |?       |       |        |     |
|HS                                       |?       |       |        |     |
|iteRates                                 |?       |       |        |     |
|NSM3                                     |?       |       |        |     |
|[permutations](failures.md#permutations) |1.0-6   |__+1__ |        |     |

**Pull request merged**
